# Generated by Django 3.2.5 on 2022-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccgp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('title', models.TextField(verbose_name='标题')),
                ('purchaser', models.CharField(default='', max_length=50, verbose_name='采购人')),
                ('agency', models.CharField(default='', max_length=50, verbose_name='代理机构')),
                ('announce_type', models.CharField(default='', max_length=10, verbose_name='公告类型')),
                ('province', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='省份')),
                ('txt', models.TextField(default='', verbose_name='文本')),
                ('map', models.TextField(default='', verbose_name='公告概要')),
                ('link', models.CharField(max_length=100, unique=True, verbose_name='链接')),
                ('domain', models.CharField(max_length=30, verbose_name='域名')),
            ],
        ),
    ]
