# Generated by Django 3.2.5 on 2022-06-18 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, verbose_name='域名')),
            ],
        ),
        migrations.CreateModel(
            name='ccgp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='标题')),
                ('purchaser', models.CharField(max_length=50, verbose_name='采购人')),
                ('agency', models.CharField(max_length=50, verbose_name='代理机构')),
                ('announce_type', models.CharField(max_length=10, verbose_name='公告类型')),
                ('province', models.CharField(max_length=10, verbose_name='省份')),
                ('txt', models.TextField(default='', verbose_name='文本')),
                ('map', models.TextField(default='', verbose_name='公告概要')),
                ('link', models.CharField(max_length=100, unique=True, verbose_name='链接')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.host', verbose_name='host')),
            ],
        ),
    ]
