# Generated by Django 3.2.5 on 2022-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='账号')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('status', models.SmallIntegerField(choices=[(0, '停用'), (1, '正常')], default=0, verbose_name='状态')),
                ('level', models.SmallIntegerField(choices=[(1, '正常用户'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='级别')),
            ],
        ),
    ]
