# Generated by Django 3.2.5 on 2022-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=30, unique=True, verbose_name='邮箱'),
        ),
    ]
