# Generated by Django 3.2.5 on 2022-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '正常用户'), (2, '2级'), (3, '3级'), (4, '4级')], default=1, verbose_name='等级'),
        ),
    ]
