# Generated by Django 3.2.5 on 2022-06-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccgp',
            name='agency',
            field=models.CharField(default='', max_length=100, verbose_name='代理机构'),
        ),
        migrations.AlterField(
            model_name='ccgp',
            name='province',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='ccgp',
            name='purchaser',
            field=models.CharField(default='', max_length=100, verbose_name='采购人'),
        ),
    ]
